apiVersion: v2
name: auth-proxy-chart
description: A Helm chart for Kubernetes

type: application

version: 0.1.3

appVersion: "0.1.3"

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - auth-database
