replicaCount: 1

fullnameOverride: "auth"

image:
  repository: sergeivb/simple-api-gateway-auth-proxy

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: "developer"
  postgresqlPassword: "123"
  postgresqlDatabase: "auth"
  persistence:
    size: 0.1Gi
  service:
    port: "5432"
