replicaCount: 1

fullnameOverride: "auth"

image: "auth:0.1.0"  # TODO: dockerhub

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: "developer"
  postgresqlPassword: "123"
  postgresqlDatabase: "auth"
  persistence:
    size: 0.1Gi
  service:
    port: "5432"

ingress:
  enabled: false  # TODO: why?
  hosts:
    - host: arch.homework
      paths: ["/auth"]
